#! /bin/sh

WALLPAPER="$HOME/Development/Repos/dotfiles/wallpapers/nord.png"
PICOM_FLAGS="--backend=glx --unredir-if-possible --experimental-backends --vsync"

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom $PICOM_FLAGS &

xwallpaper --stretch "$WALLPAPER"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
